# Generated by Django 6.0.7 on 2026-07-15 23:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Armamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, unique=True, verbose_name='Código')),
                ('numero_serie', models.CharField(max_length=100, unique=True, verbose_name='Número de Serie')),
                ('marca', models.CharField(max_length=100)),
                ('modelo', models.CharField(max_length=100)),
                ('calibre', models.CharField(max_length=50)),
                ('numero_inventario', models.CharField(max_length=30, unique=True)),
                ('anio_fabricacion', models.PositiveIntegerField()),
                ('estado', models.CharField(choices=[('DISPONIBLE', 'Disponible'), ('PRESTADO', 'Prestado'), ('MANTENIMIENTO', 'Mantenimiento'), ('BAJA', 'Baja')], default='DISPONIBLE', max_length=20)),
                ('fecha_ingreso', models.DateField()),
                ('observaciones', models.TextField(blank=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Armamento',
                'verbose_name_plural': 'Armamentos',
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='Responsable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grado', models.CharField(choices=[('SLDO', 'Soldado'), ('CBOP', 'Cabo Primero'), ('CBOS', 'Cabo Segundo'), ('SGOS', 'Sargento Segundo'), ('SGOP', 'Sargento Primero'), ('SUBP', 'Suboficial Primero'), ('SUBM', 'Suboficial Mayor'), ('TNTE', 'Teniente'), ('CAPT', 'Capitán'), ('MAYO', 'Mayor'), ('TCNL', 'Teniente Coronel'), ('CRNL', 'Coronel')], max_length=5)),
                ('cedula', models.CharField(max_length=10, unique=True)),
                ('nombres', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('cargo', models.CharField(max_length=100)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Responsable',
                'verbose_name_plural': 'Responsables',
                'ordering': ['apellidos'],
            },
        ),
        migrations.CreateModel(
            name='TipoArmamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Nombre')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
            ],
            options={
                'verbose_name': 'Tipo de Armamento',
                'verbose_name_plural': 'Tipos de Armamento',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Ubicacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Ubicación',
                'verbose_name_plural': 'Ubicaciones',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Mantenimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('descripcion', models.TextField()),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('EN_PROCESO', 'En proceso'), ('FINALIZADO', 'Finalizado')], default='PENDIENTE', max_length=20)),
                ('tecnico', models.CharField(max_length=150)),
                ('armamento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mantenimientos', to='inventario.armamento')),
            ],
            options={
                'verbose_name': 'Mantenimiento',
                'verbose_name_plural': 'Mantenimientos',
                'ordering': ['-fecha_inicio'],
            },
        ),
        migrations.CreateModel(
            name='Movimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('INGRESO', 'Ingreso'), ('SALIDA', 'Salida'), ('PRESTAMO', 'Préstamo'), ('DEVOLUCION', 'Devolución'), ('MANTENIMIENTO', 'Mantenimiento'), ('CAMBIO_UBICACION', 'Cambio de ubicación'), ('CAMBIO_RESPONSABLE', 'Cambio de responsable'), ('BAJA', 'Baja')], max_length=25)),
                ('estado_anterior', models.CharField(blank=True, max_length=20)),
                ('estado_nuevo', models.CharField(blank=True, max_length=20)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('observacion', models.TextField(blank=True)),
                ('armamento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimientos', to='inventario.armamento')),
            ],
            options={
                'verbose_name': 'Movimiento',
                'verbose_name_plural': 'Movimientos',
                'ordering': ['-fecha'],
            },
        ),
    ]
