# Generated by Django 6.0.7 on 2026-07-15 23:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventario', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='movimiento',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='movimiento',
            name='responsable_anterior',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimientos_anterior', to='inventario.responsable'),
        ),
        migrations.AddField(
            model_name='movimiento',
            name='responsable_nuevo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimientos_nuevo', to='inventario.responsable'),
        ),
        migrations.AddField(
            model_name='armamento',
            name='responsable',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='armamentos', to='inventario.responsable'),
        ),
        migrations.AddField(
            model_name='armamento',
            name='tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='armamentos', to='inventario.tipoarmamento'),
        ),
        migrations.AddField(
            model_name='movimiento',
            name='ubicacion_destino',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimientos_destino', to='inventario.ubicacion'),
        ),
        migrations.AddField(
            model_name='movimiento',
            name='ubicacion_origen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimientos_origen', to='inventario.ubicacion'),
        ),
        migrations.AddField(
            model_name='armamento',
            name='ubicacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='armamentos', to='inventario.ubicacion'),
        ),
    ]
