# Generated by Django 6.0.7 on 2026-07-16 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimiento',
            name='estado_anterior',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='movimiento',
            name='estado_nuevo',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='movimiento',
            name='observacion',
            field=models.TextField(blank=True, null=True),
        ),
    ]
