# Generated by Django 6.0.7 on 2026-07-16 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0003_alter_movimiento_estado_anterior_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ubicacion',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='ubicacion',
            name='edificio',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='ubicacion',
            name='piso',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
