# Generated by Django 6.0.7 on 2026-07-16 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0004_ubicacion_activo_ubicacion_edificio_ubicacion_piso'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipoarmamento',
            name='activo',
            field=models.BooleanField(default=True, verbose_name='Activo'),
        ),
        migrations.AlterField(
            model_name='tipoarmamento',
            name='descripcion',
            field=models.TextField(blank=True, default='', verbose_name='Descripción'),
            preserve_default=False,
        ),
    ]
