# Generated by Django 6.0.7 on 2026-07-16 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0005_tipoarmamento_activo_alter_tipoarmamento_descripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimiento',
            name='estado_nuevo',
            field=models.CharField(blank=True, choices=[('DISPONIBLE', 'Disponible'), ('PRESTADO', 'Prestado'), ('MANTENIMIENTO', 'Mantenimiento'), ('BAJA', 'Baja')], max_length=20, null=True),
        ),
    ]
