# Generated by Django 6.0.7 on 2026-07-16 22:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0006_alter_movimiento_estado_nuevo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mantenimiento',
            options={'ordering': ['-fecha_ingreso'], 'verbose_name': 'Mantenimiento', 'verbose_name_plural': 'Mantenimientos'},
        ),
        migrations.RenameField(
            model_name='mantenimiento',
            old_name='fecha_inicio',
            new_name='fecha_ingreso',
        ),
        migrations.RenameField(
            model_name='mantenimiento',
            old_name='fecha_fin',
            new_name='fecha_salida',
        ),
    ]
