# Generated by Django 6.0.7 on 2026-07-17 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0007_alter_mantenimiento_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mantenimiento',
            name='motivo',
            field=models.CharField(default='Registro anterior', max_length=200),
            preserve_default=False,
        ),
    ]
