# Generated by Django 6.0.7 on 2026-07-17 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0008_mantenimiento_motivo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mantenimiento',
            name='motivo',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
