# Generated by Django 6.0.7 on 2026-07-17 02:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0009_alter_mantenimiento_motivo'),
    ]

    operations = [
        migrations.AddField(
            model_name='mantenimiento',
            name='responsable_destino',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='mantenimientos_responsable', to='inventario.responsable'),
        ),
        migrations.AddField(
            model_name='mantenimiento',
            name='ubicacion_destino',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='mantenimientos_destino', to='inventario.ubicacion'),
        ),
    ]
