# Generated by Django 6.0.7 on 2026-07-17 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0010_mantenimiento_responsable_destino_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ubicacion',
            name='es_taller',
            field=models.BooleanField(default=False, verbose_name='Es taller de mantenimiento'),
        ),
    ]
