# Generated by Django 6.0.7 on 2026-07-31 19:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0013_armamento_duenio'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimiento',
            name='duenio_anterior',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimientos_duenio_anterior', to='inventario.alumno'),
        ),
        migrations.AddField(
            model_name='movimiento',
            name='duenio_nuevo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimientos_duenio_nuevo', to='inventario.alumno'),
        ),
        migrations.AlterField(
            model_name='armamento',
            name='estado',
            field=models.CharField(choices=[('OPERABLE', 'Operable'), ('MANTENIMIENTO', 'Mantenimiento'), ('NO_OPERABLE', 'No Operable')], default='OPERABLE', max_length=20),
        ),
        migrations.AlterField(
            model_name='movimiento',
            name='estado_nuevo',
            field=models.CharField(blank=True, choices=[('OPERABLE', 'Operable'), ('MANTENIMIENTO', 'Mantenimiento'), ('NO_OPERABLE', 'No Operable')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='movimiento',
            name='tipo',
            field=models.CharField(choices=[('INGRESO', 'Ingreso'), ('CAMBIO_UBICACION', 'Cambio de ubicación'), ('CAMBIO_RESPONSABLE', 'Cambio de responsable del armerillo'), ('CAMBIO_DUENIO', 'Cambio de dueño'), ('NO_OPERABLE', 'Marcar como No Operable')], max_length=25),
        ),
    ]
