# Generated by Django 6.0.7 on 2026-07-31 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0014_movimiento_duenio_anterior_movimiento_duenio_nuevo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='armamento',
            name='anio_fabricacion',
        ),
        migrations.RemoveField(
            model_name='armamento',
            name='numero_inventario',
        ),
    ]
