# Generated by Django 6.0.7 on 2026-08-01 00:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0015_remove_armamento_anio_fabricacion_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mantenimiento',
            name='tecnico',
        ),
        migrations.AddField(
            model_name='mantenimiento',
            name='responsable_armerillo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='mantenimientos_tecnico', to='inventario.responsable', verbose_name='Responsable del armerillo'),
        ),
    ]
