# Generated by Django 6.0.7 on 2026-08-03 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0016_remove_mantenimiento_tecnico_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='armamento',
            name='fecha_ingreso',
        ),
    ]
