# Generated by Django 6.0.7 on 2026-08-09 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0017_remove_armamento_fecha_ingreso'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumno',
            name='especialidad',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='alumno',
            name='grado',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='alumno',
            name='novedades',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='movimiento',
            name='tipo',
            field=models.CharField(choices=[('INGRESO', 'Ingreso'), ('CAMBIO_UBICACION', 'Cambio de ubicación'), ('CAMBIO_RESPONSABLE', 'Cambio de responsable del armerillo'), ('CAMBIO_DUENIO', 'Cambio de dueño'), ('NO_OPERABLE', 'Marcar como No Operable'), ('BAJA', 'Dar de baja')], max_length=25),
        ),
    ]
