# Generated by Django 6.0.7 on 2026-08-12 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0018_alumno_especialidad_alumno_grado_alumno_novedades_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimiento',
            name='tipo',
            field=models.CharField(choices=[('INGRESO', 'Ingreso'), ('SALIDA', 'Salida de armamento'), ('ENTRADA', 'Entrada de armamento'), ('CAMBIO_UBICACION', 'Cambio de ubicación'), ('CAMBIO_RESPONSABLE', 'Cambio de responsable del armerillo'), ('CAMBIO_DUENIO', 'Cambio de dueño'), ('NO_OPERABLE', 'Marcar como No Operable'), ('BAJA', 'Dar de baja')], max_length=25),
        ),
    ]
