# Generated by Django 6.0.7 on 2026-08-14 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0019_alter_movimiento_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimiento',
            name='registrado_qr',
            field=models.BooleanField(default=False),
        ),
    ]
